### ISSUE TITLE
Error extracting single bundles

### ISSUE THREAD

**Issue by steam-test1** [Luffyyy/Diesel-Bundle-Modder#4]
```
Unhandled Thread Exception
====
Is Linux = False
====
System.ArgumentOutOfRangeException: Value of '-2147483648' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at PDBundleModPatcher.MainForm.UpdateProgressTick(Object sender, EventArgs args)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
====
```

**Comment by CDTH06** [comment]
Can you please tell me how you solve it?
